[{
	"id": "2",
	"verses": "Holy Father, may they be one as we are one.' ",
	"book": "John",
	"chapter": "17",
	"verse_num": "11",
	"christ_word": "2",
	"testament": "1",
	"tag": "Prayer",
	"timestamp": "2015-02-20 08:59:13",
	"description": "Jesus prayed: 'Holy Father, may they be one, as we are.'"
}, {
	"id": "3",
	"verses": "A sward will pierce through your soul so the thoughts of many hearts may be revealed. ",
	"book": "Luke",
	"chapter": "2",
	"verse_num": "35",
	"christ_word": "21",
	"testament": "1",
	"tag": "Suffering",
	"timestamp": "2015-02-20 22:52:31",
	"description": "(Yea, a sword shall pierce through thy own soul also,) that the thoughts of many hearts may be revealed."
}, {
	"id": "4",
	"verses": "What is impossible with man is possible with God.",
	"book": "Luke",
	"chapter": "18",
	"verse_num": "27",
	"christ_word": "2",
	"testament": "1",
	"tag": "Encouragement",
	"timestamp": "2015-02-03 05:02:01",
	"description": "The things which are impossible with men is possible with God."
}, {
	"id": "5",
	"verses": "He was pierced for our transgressions, he was crushed for our iniquities.",
	"book": "Isaiah",
	"chapter": "53",
	"verse_num": "5",
	"christ_word": "22",
	"testament": "0",
	"tag": "Suffering",
	"timestamp": "2015-02-23 05:23:18",
	"description": "He was wounded for our transgressions, he was bruised for our iniquities."
}, {
	"id": "6",
	"verses": "I will pour out my spirit upon all flesh; and your sons and your daughters shall prophesy, your old men shall dream dreams, your young men shall see visions.",
	"book": "Joel",
	"chapter": "2",
	"verse_num": "28",
	"christ_word": "26",
	"testament": "0",
	"tag": "Prophesy",
	"timestamp": "2015-03-10 12:20:31",
	"description": "I will pour out my spirit upon all flesh; and your sons and your daughters shall prophesy, your old men shall dream dreams, your young men shall see visions."
}, {
	"id": "7",
	"verses": "If the son sets you free, you will be free indeed.",
	"book": "John",
	"chapter": "8",
	"verse_num": "36",
	"christ_word": "2",
	"testament": "1",
	"tag": "Freedom",
	"timestamp": "2015-02-03 06:18:37",
	"description": "If the Son therefore shall make you free, ye shall be free indeed."
}, {
	"id": "8",
	"verses": "When the dead rise, they will neither marry nor be given in marriage; they will be like the angels in heaven.",
	"book": "Mark",
	"chapter": "12",
	"verse_num": "25",
	"christ_word": "2",
	"testament": "1",
	"tag": "Resurrection",
	"timestamp": "2015-03-10 12:34:24",
	"description": "For when they shall rise from the dead, they neither marry, nor are given in marriage; but are as the angels which are in heaven."
}, {
	"id": "9",
	"verses": "Do not fear, only believe.",
	"book": "Mark",
	"chapter": "5",
	"verse_num": "36",
	"christ_word": "3",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-03-10 13:35:37",
	"description": "Be not afraid, only believe."
}, {
	"id": "10",
	"verses": "If anyone hears my words and does not keep them, I do not judge him; for I did not come to judge the world but to save the world.",
	"book": "John",
	"chapter": "12",
	"verse_num": "47",
	"christ_word": "3",
	"testament": "1",
	"tag": "Mercy",
	"timestamp": "2015-03-10 13:40:45",
	"description": "If any man hear my words, and believe not, I judge him not: For I came not to judge the world but to save the world."
}, {
	"id": "11",
	"verses": "Unless you see signs and wonders you will not believe.",
	"book": "John",
	"chapter": "4",
	"verse_num": "48",
	"christ_word": "3",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-02-04 14:37:08",
	"description": "Except ye see signs and wonders, ye will not believe."
}, {
	"id": "12",
	"verses": "What good is it for someone to gain the whole world, yet forfeit their soul?",
	"book": "Mark",
	"chapter": "8",
	"verse_num": "36",
	"christ_word": "2",
	"testament": "1",
	"tag": "Possession",
	"timestamp": "2015-03-11 11:23:57",
	"description": "For what shall it profit a man, if he shall gain the whole world, and lose his own soul?"
}, {
	"id": "13",
	"verses": "If God is for us, who can be against us?",
	"book": "Romans",
	"chapter": "8",
	"verse_num": "31",
	"christ_word": "22",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-03-11 11:28:46",
	"description": "If God be for us, who can be against us?"
}, {
	"id": "14",
	"verses": "Return, O my soul, to your rest; for the Lord has dealt bountifully with you.",
	"book": "Psalm",
	"chapter": "116",
	"verse_num": "7",
	"christ_word": "21",
	"testament": "0",
	"tag": "Peace",
	"timestamp": "2015-04-11 00:42:53",
	"description": "Return unto thy rest, O my soul, for the Lord hath dealt bountifully with thee."
}, {
	"id": "15",
	"verses": "I have been crucified with Christ. It is no longer I who live, but Christ who lives in me.",
	"book": "Galatians",
	"chapter": "2",
	"verse_num": "20",
	"christ_word": "21",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-04-11 02:55:42",
	"description": "I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me."
}, {
	"id": "16",
	"verses": "Arise, plead your case before the mountains, and let the hills hear your voice.\r\n",
	"book": "Micah",
	"chapter": "6",
	"verse_num": "1",
	"christ_word": "21",
	"testament": "0",
	"tag": "Confession",
	"timestamp": "2015-04-11 04:15:26",
	"description": "Arise, contend thou before the mountains, and let the hills hear thy voice.\r\n"
}, {
	"id": "17",
	"verses": "For I was hungry and you gave me food, I was thirsty and you gave me drink, I was a stranger and you welcomed me, I was naked and you clothed me, I was sick and you visited me, I was in prison and you came to me.",
	"book": "Matthew",
	"chapter": "25",
	"verse_num": "35-36",
	"christ_word": "3",
	"testament": "1",
	"tag": "Grace",
	"timestamp": "2015-04-11 08:13:57",
	"description": "For I was an hungred, and ye gave me meat: I was thirsty and ye gave me drink: I was a stranger, and ye took me in: Naked, and ye clothed me: I was sick, and ye visited me: I was in prison, and ye came unto me."
}, {
	"id": "18",
	"verses": "In wrath remember mercy.",
	"book": "Habakkuk",
	"chapter": "3",
	"verse_num": "2",
	"christ_word": "22",
	"testament": "0",
	"tag": "Mercy",
	"timestamp": "2015-04-11 08:27:21",
	"description": "In wrath remember mercy."
}, {
	"id": "19",
	"verses": "For as by one man's disobedience the many were made sinners, so by the one man's obedience the many will be made righteous.",
	"book": "Romans",
	"chapter": "5",
	"verse_num": "19",
	"christ_word": "21",
	"testament": "1",
	"tag": "Obedience",
	"timestamp": "2015-04-11 10:40:36",
	"description": "For as by one man's disobedience many were made sinners, so by the obedience of one shall many be made righteous."
}, {
	"id": "20",
	"verses": "He will tend his flock like a shepherd; he will gather the lambs in his arms; he will carry them in his bosom, and gently lead those that are with young.",
	"book": "Isaiah",
	"chapter": "40",
	"verse_num": "11",
	"christ_word": "21",
	"testament": "0",
	"tag": "Prophesy",
	"timestamp": "2015-04-11 11:02:08",
	"description": "He shall feed his flock like a shepherd: he shall gather the lambs with his arm, and carry them in his bosom, and shall gently lead those that are with young."
}, {
	"id": "21",
	"verses": "Whatever you ask in prayer, believe that you have received it, and it will be yours.",
	"book": "Mark",
	"chapter": "11",
	"verse_num": "24",
	"christ_word": "2",
	"testament": "1",
	"tag": "Prayer",
	"timestamp": "2015-04-11 11:33:01",
	"description": "Therefore I say unto you, What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them."
}, {
	"id": "22",
	"verses": "Solomon said to God, \"Give me wisdom and knowledge that I may lead this people.\"",
	"book": "2 Chronicles",
	"chapter": "1",
	"verse_num": "10",
	"christ_word": "22",
	"testament": "0",
	"tag": "Wisdom",
	"timestamp": "2015-04-11 11:59:17",
	"description": "Solomon answered God, \"Give me now wisdom and knowledge, that I may go out and come in before this people\"\r\n"
}, {
	"id": "23",
	"verses": "Where two or three are gathered in my name, there am I in their midst.",
	"book": "Matthew",
	"chapter": "18",
	"verse_num": "20",
	"christ_word": "7",
	"testament": "1",
	"tag": "Prayer",
	"timestamp": "2015-04-12 08:55:24",
	"description": "For where two or three are gathered together in my name, there am I in the midst of them."
}, {
	"id": "24",
	"verses": "You are precious...",
	"book": "Isaiah",
	"chapter": "43",
	"verse_num": "4",
	"christ_word": "21",
	"testament": "0",
	"tag": "Hope",
	"timestamp": "2015-04-12 10:12:34",
	"description": "Since thou wast precious in my sight, thou hast been honourable, and I have loved thee: therefore will I give men for thee, and people for thy life.\r\n"
}, {
	"id": "25",
	"verses": "Everyone who drinks this water will be thirsty again, but whoever drinks the water I give them will never thirst. Indeed, the water I give them will become in them a spring of water welling up to eternal life.",
	"book": "John",
	"chapter": "4",
	"verse_num": "13-14",
	"christ_word": "2",
	"testament": "1",
	"tag": "Grace",
	"timestamp": "2015-04-12 11:46:52",
	"description": "Whosoever drinketh of this water shall thirst again: But whosoever drinketh of the water that I shall give him shall never thirst; but the water that I shall give him shall be in him a well of water springing up into everlasting life."
}, {
	"id": "26",
	"verses": "Open rebuke is better than hidden love.",
	"book": "Proverbs",
	"chapter": "27",
	"verse_num": "5",
	"christ_word": "26",
	"testament": "0",
	"tag": "Rebuke",
	"timestamp": "2015-04-12 23:28:02",
	"description": "Open rebuke is better than secret love."
}, {
	"id": "27",
	"verses": "I myself serve the law of God with my mind, but with my flesh I serve the law of sin.",
	"book": "Romans",
	"chapter": "7",
	"verse_num": "25",
	"christ_word": "21",
	"testament": "1",
	"tag": "Sin",
	"timestamp": "2015-04-13 00:07:10",
	"description": "With the mind I myself serve the law of God; but with the flesh the law of sin."
}, {
	"id": "28",
	"verses": "He will swallow up death forever; and the Lord God will wipe away tears from all faces.",
	"book": "Isaiah ",
	"chapter": "25",
	"verse_num": "8",
	"christ_word": "21",
	"testament": "0",
	"tag": "Prophesy",
	"timestamp": "2015-04-13 00:23:41",
	"description": "He will swallow up death in victory; and the Lord GOD will wipe away tears from off all faces."
}, {
	"id": "29",
	"verses": "Because you have seen me, you have believed; blessed are those who have not seen and yet have believed.",
	"book": "John",
	"chapter": "20",
	"verse_num": "29",
	"christ_word": "2",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-04-13 10:41:44",
	"description": "Because thou hast seen me, thou hast believed: blessed are they that have not seen, and yet have believed."
}, {
	"id": "30",
	"verses": "He who is slow to anger has great understanding.",
	"book": "Proverbs",
	"chapter": "14",
	"verse_num": "29",
	"christ_word": "25",
	"testament": "0",
	"tag": "Anger",
	"timestamp": "2015-04-13 22:56:23",
	"description": "He that is slow to wrath is of great understanding."
}, {
	"id": "31",
	"verses": "For now we see in a mirror dimly, but then face to face. Now I know in part; then I shall know fully, even as I have been fully known.",
	"book": "1 Corinthians",
	"chapter": "13",
	"verse_num": "12",
	"christ_word": "21",
	"testament": "1",
	"tag": "Wisdom",
	"timestamp": "2015-04-14 00:24:13",
	"description": "For now we see through a glass, darkly; but then face to face: now I know in part; but then shall I know even as also I am known."
}, {
	"id": "32",
	"verses": "Call to me and I will answer you, and will tell you great and hidden things that you have not known.",
	"book": "Jeremiah",
	"chapter": "33",
	"verse_num": "3",
	"christ_word": "21",
	"testament": "0",
	"tag": "Prayer",
	"timestamp": "2015-04-14 03:14:08",
	"description": "Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not.\r\n"
}, {
	"id": "33",
	"verses": "God is spirit, and those who worship him must worship in spirit and truth.",
	"book": "John",
	"chapter": "4",
	"verse_num": "24",
	"christ_word": "3",
	"testament": "1",
	"tag": "Worship",
	"timestamp": "2015-04-14 03:35:42",
	"description": "God is a Spirit: and they that worship him must worship him in spirit and in truth."
}, {
	"id": "34",
	"verses": "All the paths of the Lord are steadfast love and faithfulness, for those who keep his covenant and his testimonies.",
	"book": "Psalm",
	"chapter": "25",
	"verse_num": "10",
	"christ_word": "21",
	"testament": "0",
	"tag": "Faith",
	"timestamp": "2015-04-20 11:57:40",
	"description": "All the paths of the Lord are mercy and truth unto such as keep his covenant and his testimonies."
}, {
	"id": "35",
	"verses": "Come to me, all you who are weary and burdened, and I will give you rest.",
	"book": "Matthew",
	"chapter": "11",
	"verse_num": "28",
	"christ_word": "2",
	"testament": "1",
	"tag": "Peace",
	"timestamp": "2015-04-20 12:36:31",
	"description": "Come unto me, all ye that labour and are heavy laden, and I will give you rest."
}, {
	"id": "36",
	"verses": "Blessed is the man against whom the Lord counts no iniquity, and in whose spirit there is no deceit.",
	"book": "Psalm",
	"chapter": "32",
	"verse_num": "2",
	"christ_word": "21",
	"testament": "0",
	"tag": "Deceit",
	"timestamp": "2015-04-20 12:45:11",
	"description": "Blessed is the man unto whom the Lord imputeth not iniquity, and in whose spirit there is no guile."
}, {
	"id": "37",
	"verses": "Whoever does not love does not know God, because God is love.",
	"book": "1 John",
	"chapter": "4",
	"verse_num": "8",
	"christ_word": "22",
	"testament": "1",
	"tag": "Love",
	"timestamp": "2015-04-20 12:58:27",
	"description": "He that loveth not knoweth not God; for God is love."
}, {
	"id": "38",
	"verses": "Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go.",
	"book": "Joshua",
	"chapter": "1",
	"verse_num": "9",
	"christ_word": "22",
	"testament": "0",
	"tag": "Courage",
	"timestamp": "2015-04-20 20:04:17",
	"description": "Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest."
}, {
	"id": "39",
	"verses": "So we fix our eyes not on what is seen, but on what is unseen, since what is seen is temporary, but what is unseen is eternal.\r\n",
	"book": "2 Corinthians",
	"chapter": "4",
	"verse_num": "18",
	"christ_word": "22",
	"testament": "1",
	"tag": "Eternity",
	"timestamp": "2015-04-21 11:20:12",
	"description": "While we look not at the things which are seen, but at the things which are not seen: for the things which are seen are temporal; but the things which are not seen are eternal."
}, {
	"id": "40",
	"verses": "The LORD does not look at the things people look at. People look at the outward appearance, but the LORD looks at the heart.",
	"book": "1 Samuel",
	"chapter": "16",
	"verse_num": "7",
	"christ_word": "22",
	"testament": "0",
	"tag": "Beauty",
	"timestamp": "2015-04-22 11:41:53",
	"description": "The LORD seeth not as man seeth; for man looketh on the outward appearance, but the LORD looketh on the heart.\r\n"
}, {
	"id": "41",
	"verses": "God opposes the proud but gives grace to the humble.",
	"book": "1 Peter",
	"chapter": "5",
	"verse_num": "5",
	"christ_word": "21",
	"testament": "1",
	"tag": "Pride",
	"timestamp": "2015-04-23 12:17:25",
	"description": "God resisteth the proud, and giveth grace to the humble."
}, {
	"id": "42",
	"verses": "For everything there is a season, and a time for every matter under heaven.",
	"book": "Ecclesiastes",
	"chapter": "3",
	"verse_num": "1",
	"christ_word": "21",
	"testament": "0",
	"tag": "Providence",
	"timestamp": "2015-04-24 11:33:12",
	"description": "To every thing there is a season, and a time to every purpose under the heaven."
}, {
	"id": "43",
	"verses": "Love is patient and kind; love does not envy or boast; it is not arrogant or rude. It does not insist on its own way; it is not irritable or resentful; it does not rejoice at wrongdoing, but rejoices with the truth. Love bears all things, believes all things, hopes all things, endures all things. Love never ends.",
	"book": "1 Corinthians",
	"chapter": "13",
	"verse_num": "4-8",
	"christ_word": "21",
	"testament": "1",
	"tag": "Love",
	"timestamp": "2015-04-25 10:52:04",
	"description": "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up, Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil; Rejoiceth not in iniquity, but rejoiceth in the truth; Beareth all things, believeth all things, hopeth all things, endureth all things. Charity never faileth."
}, {
	"id": "44",
	"verses": "Then I heard the voice of the Lord saying, \"Whom shall I send? And who will go for us?\" And I said, \"Here am I. Send me.\"\r\n",
	"book": "Isaiah",
	"chapter": "6",
	"verse_num": "8",
	"christ_word": "22",
	"testament": "0",
	"tag": "Courage",
	"timestamp": "2015-04-26 11:39:13",
	"description": "Also I heard the voice of the Lord, saying, Whom shall I send, and who will go for us? Then said I, Here am I; send me.\r\n"
}, {
	"id": "45",
	"verses": "God shows no partiality, but in every nation anyone who fears him and does what is right is acceptable to him.",
	"book": "Acts",
	"chapter": "10",
	"verse_num": "34-35",
	"christ_word": "21",
	"testament": "1",
	"tag": "Favoritism",
	"timestamp": "2015-04-27 10:53:18",
	"description": "God is no respecter of persons: But in every nation he that feareth him, and worketh righteousness, is accepted with him."
}, {
	"id": "46",
	"verses": "Do not seek revenge or bear a grudge against anyone among your people, but love your neighbor as yourself. I am the LORD.",
	"book": "Leviticus",
	"chapter": "19",
	"verse_num": "18",
	"christ_word": "22",
	"testament": "0",
	"tag": "Love",
	"timestamp": "2015-04-28 11:19:37",
	"description": "Thou shalt not avenge, nor bear any grudge against the children of thy people, but thou shalt love thy neighbour as thyself: I am the LORD."
}, {
	"id": "47",
	"verses": "I came that they may have life and have it abundantly.",
	"book": "John",
	"chapter": "10",
	"verse_num": "10",
	"christ_word": "3",
	"testament": "1",
	"tag": "Grace",
	"timestamp": "2015-04-29 10:04:21",
	"description": "I am come that they might have life, and that they might have it more abundantly.\r\n"
}, {
	"id": "48",
	"verses": "Because of the LORD's great love we are not consumed, for his compassions never fail.",
	"book": "Lamentations",
	"chapter": "3",
	"verse_num": "22",
	"christ_word": "22",
	"testament": "0",
	"tag": "Love",
	"timestamp": "2015-04-30 10:08:26",
	"description": "It is of the LORD'S mercies that we are not consumed, because his compassions fail not."
}, {
	"id": "49",
	"verses": "Every good and perfect gift is from above.",
	"book": "James",
	"chapter": "1",
	"verse_num": "17",
	"christ_word": "22",
	"testament": "1",
	"tag": "Perfection",
	"timestamp": "2015-05-01 05:16:48",
	"description": "Every good gift and every perfect gift is from above."
}, {
	"id": "50",
	"verses": "He heals the brokenhearted and binds up their wounds.\r\n",
	"book": "Psalm",
	"chapter": "147",
	"verse_num": "3",
	"christ_word": "22",
	"testament": "0",
	"tag": "Healing",
	"timestamp": "2015-05-02 10:03:24",
	"description": "He healeth the broken in heart, and bindeth up their wounds.\r\n"
}, {
	"id": "51",
	"verses": "For the Son of Man came to seek and to save the lost.",
	"book": "Luke",
	"chapter": "19",
	"verse_num": "10",
	"christ_word": "2",
	"testament": "1",
	"tag": "Savior",
	"timestamp": "2015-05-03 10:12:46",
	"description": "For the Son of man is come to seek and to save that which was lost."
}, {
	"id": "52",
	"verses": "When I said, My foot slips; your mercy, O LORD, held me up.",
	"book": "Psalm",
	"chapter": "94",
	"verse_num": "18",
	"christ_word": "25",
	"testament": "0",
	"tag": "Love",
	"timestamp": "2015-05-04 12:10:23",
	"description": "When I said, My foot slippeth; thy mercy, O LORD, held me up."
}, {
	"id": "53",
	"verses": "Whoever loses his life for my sake will find it.",
	"book": "Matthew",
	"chapter": "16",
	"verse_num": "25",
	"christ_word": "3",
	"testament": "1",
	"tag": "Sacrifice",
	"timestamp": "2015-05-05 09:47:08",
	"description": "Whosoever will lose his life for my sake shall find it.\r\n"
}, {
	"id": "54",
	"verses": "For our struggle is not against flesh and blood, but against the rulers, against the authorities, against the powers of this dark world and against the spiritual forces of evil in the heavenly realms.\r\n",
	"book": "Ephesians",
	"chapter": "6",
	"verse_num": "12",
	"christ_word": "22",
	"testament": "1",
	"tag": "Government",
	"timestamp": "2015-05-06 11:08:59",
	"description": "For we wrestle not against flesh and blood, but against principalities, against powers, against the rulers of the darkness of this world, against spiritual wickedness in high places.\r\n"
}, {
	"id": "55",
	"verses": "By the sweat of your face you shall eat bread, till you return to the ground, for out of it you were taken; for you are dust, and to dust you shall return.",
	"book": "Genesis",
	"chapter": "3",
	"verse_num": "19",
	"christ_word": "21",
	"testament": "0",
	"tag": "Effort",
	"timestamp": "2015-05-06 23:47:19",
	"description": "In the sweat of thy face shalt thou eat bread, till thou return unto the ground; for out of it wast thou taken: for dust thou art, and unto dust shalt thou return."
}, {
	"id": "56",
	"verses": "Surely goodness and mercy shall follow me all the days of my life, and I shall dwell in the house of the LORD forever.",
	"book": "Psalm",
	"chapter": "23",
	"verse_num": "6",
	"christ_word": "21",
	"testament": "0",
	"tag": "Mercy",
	"timestamp": "2015-05-07 10:56:58",
	"description": "Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the LORD for ever."
}, {
	"id": "57",
	"verses": "Where there is no vision, the people perish.",
	"book": "Proverbs",
	"chapter": "29",
	"verse_num": "18",
	"christ_word": "25",
	"testament": "0",
	"tag": "Vision",
	"timestamp": "2015-05-07 21:41:39",
	"description": "Where there is no vision, the people perish."
}, {
	"id": "58",
	"verses": "Let not your hearts be troubled. Believe in God; believe also in me.",
	"book": "John",
	"chapter": "14",
	"verse_num": "1",
	"christ_word": "3",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-05-08 06:08:48",
	"description": "Let not your heart be troubled: ye believe in God, believe also in me."
}, {
	"id": "59",
	"verses": "We rejoice in our sufferings, knowing that suffering produces endurance. and endurance produces character, and character produces hope.",
	"book": "Romans",
	"chapter": "5",
	"verse_num": "3-4",
	"christ_word": "21",
	"testament": "1",
	"tag": "Suffering",
	"timestamp": "2015-05-09 10:37:22",
	"description": "We glory in tribulations also: knowing that tribulation worketh patience; And patience, experience; and experience, hope."
}, {
	"id": "60",
	"verses": "The man who formerly persecuted us is now preaching the faith he once tried to destroy.",
	"book": "Galatians",
	"chapter": "1",
	"verse_num": "23",
	"christ_word": "22",
	"testament": "1",
	"tag": "Persecution",
	"timestamp": "2015-05-10 08:14:13",
	"description": "He which persecuted us in times past now preacheth the faith which once he destroyed."
}, {
	"id": "61",
	"verses": "If serving the LORD seems undesirable to you, then choose for yourselves this day whom you will serve.",
	"book": "Joshua",
	"chapter": "24",
	"verse_num": "15",
	"christ_word": "22",
	"testament": "0",
	"tag": "Faith",
	"timestamp": "2015-05-11 05:43:58",
	"description": "If it seem evil unto you to serve the LORD, choose you this day whom ye will serve."
}, {
	"id": "62",
	"verses": "Let me hear in the morning of your steadfast love, for in you I trust. Make me know the way I should go, for to you I lift up my soul.",
	"book": "Psalm",
	"chapter": "143",
	"verse_num": "8",
	"christ_word": "21",
	"testament": "0",
	"tag": "Prayer",
	"timestamp": "2015-05-12 10:19:52",
	"description": "Cause me to hear thy lovingkindness in the morning; for in thee do I trust: cause me to know the way wherein I should walk; for I lift up my soul unto thee.\r\n"
}, {
	"id": "64",
	"verses": "And the LORD regretted that he had made man on the earth, and it grieved him to his heart.",
	"book": "Genesis",
	"chapter": "6",
	"verse_num": "6",
	"christ_word": "21",
	"testament": "0",
	"tag": "Regret",
	"timestamp": "2015-05-13 09:06:53",
	"description": "And it repented the LORD that he had made man on the earth, and it grieved him at his heart."
}, {
	"id": "65",
	"verses": "In the same way, I tell you, there is joy in the presence of the angels of God over one sinner who repents.",
	"book": "Luke",
	"chapter": "15",
	"verse_num": "10",
	"christ_word": "4",
	"testament": "1",
	"tag": "Repent",
	"timestamp": "2015-05-14 10:27:52",
	"description": "Likewise, I say unto you, there is joy in the presence of the angels of God over one sinner that repenteth."
}, {
	"id": "66",
	"verses": "The one who doubts is like a wave of the sea that is driven and tossed by the wind. For that person must not suppose that he will receive anything from the Lord.",
	"book": "James",
	"chapter": "1",
	"verse_num": "6-7",
	"christ_word": "21",
	"testament": "1",
	"tag": "Doubt",
	"timestamp": "2015-05-15 10:02:26",
	"description": "He that wavereth is like a wave of the sea driven with the wind and tossed. For let not that man think that he shall receive any thing of the Lord."
}, {
	"id": "67",
	"verses": "I can do nothing on my own. As I hear; I judge, and my judgment is just, because I seek not my own will but the will of him who sent me.",
	"book": "John",
	"chapter": "5",
	"verse_num": "30",
	"christ_word": "3",
	"testament": "1",
	"tag": "Authority",
	"timestamp": "2015-05-16 10:08:54",
	"description": "I can of mine own self do nothing: as I hear, I judge: and my judgment is just; because I seek not mine own will but the will of the Father which hath sent me."
}, {
	"id": "68",
	"verses": "Set your minds on things that are above, not on things that are on earth.",
	"book": "Colossians",
	"chapter": "3",
	"verse_num": "2",
	"christ_word": "21",
	"testament": "1",
	"tag": "Determination",
	"timestamp": "2015-05-17 10:21:17",
	"description": "Set your affection on things above, not on things on the earth."
}, {
	"id": "69",
	"verses": "The eternal God is your dwelling place, and underneath are the everlasting arms.",
	"book": "Deuteronomy",
	"chapter": "33",
	"verse_num": "27",
	"christ_word": "21",
	"testament": "0",
	"tag": "Protection",
	"timestamp": "2015-05-18 10:47:52",
	"description": "The eternal God is thy refuge, and underneath are the everlasting arms."
}, {
	"id": "70",
	"verses": "Consider the lilies, how they grow: they neither toil nor spin, yet I tell you, even Solomon in all his glory was not arrayed like one of these.",
	"book": "Luke",
	"chapter": "12",
	"verse_num": "27",
	"christ_word": "3",
	"testament": "1",
	"tag": "Stress",
	"timestamp": "2015-05-19 10:59:30",
	"description": "Consider the lilies how they grow: they toil not, they spin not; and yet I say unto you, that Solomon in all his glory was not arrayed like one of these."
}, {
	"id": "71",
	"verses": "Open my eyes that I may see wonderful things in your law.",
	"book": "Psalm",
	"chapter": "119",
	"verse_num": "18",
	"christ_word": "22",
	"testament": "0",
	"tag": "Knowledge",
	"timestamp": "2015-05-20 11:49:21",
	"description": "Open thou mine eyes, that I may behold wondrous things out of thy law."
}, {
	"id": "72",
	"verses": "The grass withers, the flower fades, but the word of our God will stand forever.",
	"book": "Isaiah",
	"chapter": "40",
	"verse_num": "8",
	"christ_word": "21",
	"testament": "0",
	"tag": "Eternity",
	"timestamp": "2015-05-21 10:49:00",
	"description": "The grass withereth, the flower fadeth: but the word of our God shall stand for ever."
}, {
	"id": "73",
	"verses": "Then you will know the truth, and the truth will set you free.",
	"book": "John",
	"chapter": "8",
	"verse_num": "32",
	"christ_word": "2",
	"testament": "1",
	"tag": "Truth",
	"timestamp": "2015-05-22 10:56:56",
	"description": "And ye shall know the truth, and the truth shall make you free."
}, {
	"id": "74",
	"verses": "I have fought the good fight, I have finished the course, I have kept the faith.",
	"book": "2 Timothy",
	"chapter": "4",
	"verse_num": "7",
	"christ_word": "24",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-05-23 11:00:04",
	"description": "I have fought a good fight, I have finished my course, I have kept the faith."
}, {
	"id": "75",
	"verses": "Do not fret because of those who are evil or be envious of those who do wrong.",
	"book": "Psalm",
	"chapter": "37",
	"verse_num": "1",
	"christ_word": "22",
	"testament": "0",
	"tag": "Anxious",
	"timestamp": "2015-05-24 10:38:48",
	"description": "Fret not thyself because of evildoers, neither be thou envious against the workers of iniquity."
}, {
	"id": "76",
	"verses": "I love those who love me, and those who seek me diligently find me.",
	"book": "Proverbs",
	"chapter": "8",
	"verse_num": "17",
	"christ_word": "21",
	"testament": "0",
	"tag": "Love",
	"timestamp": "2015-05-25 10:20:32",
	"description": "I love them that love me; and those that seek me early shall find me."
}, {
	"id": "77",
	"verses": "Give to everyone what you owe them: If you owe taxes, pay taxes; if revenue, then revenue; if respect, then respect; if honor, then honor.",
	"book": "Romans",
	"chapter": "13",
	"verse_num": "7",
	"christ_word": "22",
	"testament": "1",
	"tag": "Debt",
	"timestamp": "2015-05-26 11:31:00",
	"description": "Render therefore to all their dues: tribute to whom tribute is due; custom to whom custom; fear to whom fear; honour to whom honour."
}, {
	"id": "78",
	"verses": "For he is a chosen vessel unto me, For I will show him what great things he must suffer for my name's sake.",
	"book": "Acts",
	"chapter": "9",
	"verse_num": "15,16",
	"christ_word": "6",
	"testament": "1",
	"tag": "Chosen",
	"timestamp": "2015-05-27 09:27:55",
	"description": "For he is a chosen vessel unto me. For I will shew him how great things he must suffer for my name's sake."
}, {
	"id": "79",
	"verses": "God is light, in him there is no darkness at all.",
	"book": "1 John",
	"chapter": "1",
	"verse_num": "5",
	"christ_word": "22",
	"testament": "1",
	"tag": "Truth",
	"timestamp": "2015-05-28 09:29:44",
	"description": "God is light, and in him is no darkness at all."
}, {
	"id": "80",
	"verses": "Be of sober spirit, be on the alert. Your adversary, the devil, prowls around like a roaring lion, seeking someone to devour.",
	"book": "1 Peter",
	"chapter": "5",
	"verse_num": "8",
	"christ_word": "24",
	"testament": "1",
	"tag": "Evil",
	"timestamp": "2015-05-29 10:26:09",
	"description": "Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about, seeking whom he may devour."
}, {
	"id": "81",
	"verses": "For the LORD your God is gracious and merciful and will not turn away his face from you, if you return to him.",
	"book": "2 Chronicles",
	"chapter": "30",
	"verse_num": "9",
	"christ_word": "21",
	"testament": "0",
	"tag": "Grace",
	"timestamp": "2015-05-30 10:38:55",
	"description": "For the LORD your God is gracious and merciful, and will not turn away his face from you, if ye return unto him.\r\n"
}, {
	"id": "82",
	"verses": "Therefore do not throw away your confidence, which has a great reward. For you have need of endurance, so that when you have done the will of God you may receive what is promised.",
	"book": "Hebrews",
	"chapter": "10",
	"verse_num": "35-36",
	"christ_word": "21",
	"testament": "1",
	"tag": "Confidence",
	"timestamp": "2015-05-31 11:04:45",
	"description": "Cast not away therefore your confidence, which hath great recompence of reward. For ye have need of patience, that, after ye have done the will of God, ye might receive the promise."
}, {
	"id": "83",
	"verses": "God said to Moses, \"I AM WHO I AM.\"",
	"book": "Exodus",
	"chapter": "3",
	"verse_num": "14",
	"christ_word": "21",
	"testament": "0",
	"tag": "Divinity",
	"timestamp": "2015-06-01 09:27:30",
	"description": "And God said unto Moses, I AM THAT I AM."
}, {
	"id": "84",
	"verses": "The one who speaks on his own authority seeks his own glory; but the one who seeks the glory of him who sent him is true, and in him there is no falsehood.",
	"book": "John",
	"chapter": "7",
	"verse_num": "18",
	"christ_word": "3",
	"testament": "1",
	"tag": "Authority",
	"timestamp": "2015-06-02 09:44:49",
	"description": "He that speaketh of himself seeketh his own glory: but he that seeketh his glory that sent him, the same is true, and no unrighteousness is in him."
}, {
	"id": "85",
	"verses": "I gain understanding from your precepts... Your word is a lamp for my feet, a light on my path.",
	"book": "Psalms",
	"chapter": "119",
	"verse_num": "104,105",
	"christ_word": "22",
	"testament": "0",
	"tag": "Knowledge",
	"timestamp": "2015-06-03 10:16:38",
	"description": "Through thy precepts I get understanding... Thy word is a lamp unto my feet, and a light unto my path."
}, {
	"id": "86",
	"verses": "Be strong and courageous, do not be afraid or tremble at them, for the LORD your God is the one who goes with you. He will not fail you or forsake you.",
	"book": "Deuteronomy",
	"chapter": "31",
	"verse_num": "6",
	"christ_word": "24",
	"testament": "0",
	"tag": "Courage",
	"timestamp": "2015-06-04 11:24:23",
	"description": "Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee."
}, {
	"id": "87",
	"verses": "My ears had heard of you but now my eyes have seen you.",
	"book": "Job",
	"chapter": "42",
	"verse_num": "5",
	"christ_word": "22",
	"testament": "0",
	"tag": "Divinity",
	"timestamp": "2015-06-05 08:34:38",
	"description": "I have heard of thee by the hearing of the ear: but now mine eye seeth thee."
}, {
	"id": "88",
	"verses": "I am with you always, even to the end of the world.",
	"book": "Matthew",
	"chapter": "28",
	"verse_num": "20",
	"christ_word": "5",
	"testament": "1",
	"tag": "Eternity",
	"timestamp": "2015-06-06 09:45:27",
	"description": "I am with you alway, even unto the end of the world."
}, {
	"id": "89",
	"verses": "The heavens, even the highest heaven, cannot contain you. How much less this temple I have built!",
	"book": "1 Kings",
	"chapter": "8",
	"verse_num": "27",
	"christ_word": "22",
	"testament": "0",
	"tag": "Divinity",
	"timestamp": "2015-06-07 12:57:06",
	"description": "Behold, the heaven and heaven of heavens cannot contain thee; how much less this house that I have builded?"
}, {
	"id": "90",
	"verses": "From now on all generations will call me blessed, for the Mighty One has done great things for me -- holy is his name.",
	"book": "Luke",
	"chapter": "1",
	"verse_num": "48-49",
	"christ_word": "22",
	"testament": "1",
	"tag": "Grace",
	"timestamp": "2015-06-08 12:01:34",
	"description": "From henceforth all generations shall call me blessed. For he that is mighty hath done to me great things; and holy is his name."
}, {
	"id": "91",
	"verses": "Above all else, guard your heart, for everything you do flows from it.",
	"book": "Proverbs",
	"chapter": "4",
	"verse_num": "23",
	"christ_word": "22",
	"testament": "0",
	"tag": "Heart",
	"timestamp": "2015-06-09 10:33:50",
	"description": "Keep thy heart with all diligence; for out of it are the issues of life."
}, {
	"id": "92",
	"verses": "Man shall not live by bread alone, but by every word that comes from the mouth of God.",
	"book": "Matthew",
	"chapter": "4",
	"verse_num": "4",
	"christ_word": "3",
	"testament": "1",
	"tag": "Knowledge",
	"timestamp": "2015-06-10 11:44:26",
	"description": "Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God."
}, {
	"id": "93",
	"verses": "Without faith it is impossible to please him, for whoever would draw near to God must believe that he exists and that he rewards those who seek him.",
	"book": "Hebrews",
	"chapter": "11",
	"verse_num": "6",
	"christ_word": "21",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-06-11 11:36:35",
	"description": "Without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him."
}, {
	"id": "94",
	"verses": "For God knows that when you eat from it your eyes will be opened, and you will be like God, knowing good and evil.",
	"book": "Genesis",
	"chapter": "3",
	"verse_num": "5",
	"christ_word": "22",
	"testament": "0",
	"tag": "Knowledge",
	"timestamp": "2015-06-12 11:45:48",
	"description": "For God doth know that in the day ye eat thereof, then your eyes shall be opened, and ye shall be as gods, knowing good and evil."
}, {
	"id": "95",
	"verses": "For everyone who exalts himself will be humbled, and he who humbles himself will be exalted.",
	"book": "Luke",
	"chapter": "14",
	"verse_num": "11",
	"christ_word": "3",
	"testament": "1",
	"tag": "Humble",
	"timestamp": "2015-06-13 09:30:02",
	"description": "For whosoever exalteth himself shall be abased; and he that humbleth himself shall be exalted."
}, {
	"id": "96",
	"verses": "I will sing the LORD's praise, for he has been good to me.",
	"book": "Psalm",
	"chapter": "13",
	"verse_num": "6",
	"christ_word": "22",
	"testament": "0",
	"tag": "Prayer",
	"timestamp": "2015-06-14 08:55:29",
	"description": "I will sing unto the LORD, because he hath dealt bountifully with me."
}, {
	"id": "97",
	"verses": "Your faith should not stand in the wisdom of men, but in the power of God.",
	"book": "1 Corinthians",
	"chapter": "2",
	"verse_num": "5",
	"christ_word": "26",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-06-15 11:14:18",
	"description": "Your faith should not stand in the wisdom of men, but in the power of God."
}, {
	"id": "98",
	"verses": "I am in great distress. Let us fall into the hand of the LORD, for his mercy is great; but let me not fall into the hand of man.",
	"book": "2 Samuel",
	"chapter": "24",
	"verse_num": "14",
	"christ_word": "21",
	"testament": "0",
	"tag": "Mercy",
	"timestamp": "2015-06-16 09:35:38",
	"description": "I am in a great strait: let us fall now into the hand of the LORD; for his mercies are great: and let me not fall into the hand of man."
}, {
	"id": "99",
	"verses": "Therefore do not be anxious about tomorrow, for tomorrow will be anxious for itself. Sufficient for the day is its own trouble.",
	"book": "Matthew",
	"chapter": "6",
	"verse_num": "34",
	"christ_word": "3",
	"testament": "1",
	"tag": "Anxious",
	"timestamp": "2015-06-17 12:12:46",
	"description": "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day is the evil thereof."
}, {
	"id": "102",
	"verses": "If anyone loves the world, the love of the Father is not in him. For all that is in the world - the desires of the flesh and the desires of the eyes and pride of life - is not from the Father but is from the world. And the world is passing away along with its desires, but whoever does the will of God abides forever.",
	"book": "1 John",
	"chapter": "1",
	"verse_num": "15-17",
	"christ_word": "21",
	"testament": "1",
	"tag": "Love",
	"timestamp": "2015-06-18 11:25:22",
	"description": "If any man love the world, the love of the Father is not in him. For all that is in the world, the lust of the flesh, and the lust of the eyes, and the pride of life, is not of the Father, but is of the world. And the world passeth away, and the lust thereof: but he that doeth the will of God abideth for ever."
}, {
	"id": "103",
	"verses": "Fear not, little flock; for it is your Father's good pleasure to give you the kingdom.",
	"book": "Luke",
	"chapter": "12",
	"verse_num": "32",
	"christ_word": "5",
	"testament": "1",
	"tag": "Heaven",
	"timestamp": "2015-06-19 10:22:05",
	"description": "Fear not, little flock; for it is your Father's good pleasure to give you the kingdom."
}, {
	"id": "104",
	"verses": "Blessed is the one you discipline, LORD, the one you teach from your law.",
	"book": "Psalms",
	"chapter": "94",
	"verse_num": "12",
	"christ_word": "22",
	"testament": "0",
	"tag": "Wisdom",
	"timestamp": "2015-06-20 10:22:14",
	"description": "Blessed is the man whom thou chastenest, O LORD, and teachest him out of thy law."
}, {
	"id": "105",
	"verses": "Unless a grain of wheat falls into the earth and dies, it remains alone; but if it dies, it bears much fruit.",
	"book": "John",
	"chapter": "12",
	"verse_num": "24",
	"christ_word": "3",
	"testament": "1",
	"tag": "Life",
	"timestamp": "2015-06-21 10:58:34",
	"description": "Except a corn of wheat fall into the ground and die, it abideth alone: but if it die, it bringeth forth much fruit."
}, {
	"id": "106",
	"verses": "No eye has seen, no ear has heard, and no mind has imagined what God has prepared for those who love him.",
	"book": "1 Corinthians",
	"chapter": "2",
	"verse_num": "9",
	"christ_word": "27",
	"testament": "1",
	"tag": "Love",
	"timestamp": "2015-06-22 11:48:51",
	"description": "Eye hath not seen, nor ear heard, neither have entered into the heart of man, the things which God hath prepared for them that love him."
}, {
	"id": "107",
	"verses": "A tranquil heart gives life to the flesh, but envy makes the bones rot.",
	"book": "Proverbs",
	"chapter": "14",
	"verse_num": "30",
	"christ_word": "21",
	"testament": "0",
	"tag": "Envy",
	"timestamp": "2015-06-23 09:53:49",
	"description": "A sound heart is the life of the flesh: but envy the rottenness of the bones."
}, {
	"id": "108",
	"verses": "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.",
	"book": "Philippians",
	"chapter": "4",
	"verse_num": "6",
	"christ_word": "22",
	"testament": "1",
	"tag": "Prayer",
	"timestamp": "2015-06-24 11:59:02",
	"description": "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God."
}, {
	"id": "109",
	"verses": "This Book of the Law shall not depart from your mouth, but you shall meditate on it day and night, so that you may be careful to do according to all that is written in it. For then you will make your way prosperous, and then you will have good success.",
	"book": "Joshua",
	"chapter": "1",
	"verse_num": "8",
	"christ_word": "21",
	"testament": "0",
	"tag": "Success",
	"timestamp": "2015-06-25 12:04:04",
	"description": "This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night, that thou mayest observe to do according to all that is written therein: for then thou shalt make thy way prosperous, and then thou shalt have good success."
}, {
	"id": "110",
	"verses": "Behold, I am sending you out as sheep in the midst of wolves, so be wise as serpents and innocent as doves.",
	"book": "Matthew",
	"chapter": "10",
	"verse_num": "16",
	"christ_word": "3",
	"testament": "1",
	"tag": "Wisdom",
	"timestamp": "2015-06-26 10:28:09",
	"description": "Behold, I send you forth as sheep in the midst of wolves: be ye therefore wise as serpents, and harmless as doves."
}, {
	"id": "111",
	"verses": "There are six things that the LORD hates, seven that are an abomination to him: haughty eyes, a lying tongue, and hands that shed innocent blood, a heart that devises wicked plans, feet that make haste to run to evil, a false witness who breathes out lies, and one who sows discord among brothers.",
	"book": "Proverbs",
	"chapter": "6",
	"verse_num": "16-19",
	"christ_word": "21",
	"testament": "0",
	"tag": "Abomination",
	"timestamp": "2015-06-27 11:56:38",
	"description": "These six things doth the LORD hate: yea, seven are an abomination unto him: A proud look, a lying tongue, and hands that shed innocent blood, An heart that deviseth wicked imaginations, feet that be swift in running to mischief, A false witness that speaketh lies, and he that soweth discord among brethren."
}, {
	"id": "112",
	"verses": "So I say to you: Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.",
	"book": "Luke",
	"chapter": "11",
	"verse_num": "9",
	"christ_word": "2",
	"testament": "1",
	"tag": "Blessing",
	"timestamp": "2015-06-28 05:46:00",
	"description": "And I say unto you, Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you."
}, {
	"id": "113",
	"verses": "He has made everything beautiful in its time. He has also set eternity in the human heart; yet no one can fathom what God has done from beginning to end.",
	"book": "Ecclesiastes",
	"chapter": "3",
	"verse_num": "11",
	"christ_word": "22",
	"testament": "0",
	"tag": "Eternity",
	"timestamp": "2015-06-29 06:57:30",
	"description": "He hath made every thing beautiful in his time: also he hath set the world in their heart, so that no man can find out the work that God maketh from the beginning to the end."
}, {
	"id": "114",
	"verses": "Where you go I will go, and where you stay I will stay. Your people will be my people and your God my God.",
	"book": "Ruth",
	"chapter": "1",
	"verse_num": "16",
	"christ_word": "22",
	"testament": "0",
	"tag": "Faith",
	"timestamp": "2015-06-30 07:47:42",
	"description": "For whither thou goest, I will go; and where thou lodgest, I will lodge: thy people shall be my people, and thy God my God."
}, {
	"id": "115",
	"verses": "As the Father has loved me, so have I loved you. Now remain in my love. If you keep my commands, you will remain in my love, just as I have kept my Father's commands and remain in his love.",
	"book": "John",
	"chapter": "15",
	"verse_num": "9-10",
	"christ_word": "2",
	"testament": "1",
	"tag": "Love",
	"timestamp": "2015-07-01 07:24:41",
	"description": "As the Father hath loved me, so have I loved you: continue ye in my love. If ye keep my commandments, ye shall abide in my love; even as I have kept my Father's commandments, and abide in his love."
}, {
	"id": "116",
	"verses": "Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.",
	"book": "Isaiah",
	"chapter": "41",
	"verse_num": "10",
	"christ_word": "21",
	"testament": "0",
	"tag": "Encouragement",
	"timestamp": "2015-07-02 07:47:39",
	"description": "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness."
}, {
	"id": "118",
	"verses": "Truly I tell you, whatever you did for one of the least of these brothers and sisters of mine, you did for me.",
	"book": "Matthew",
	"chapter": "25",
	"verse_num": "40",
	"christ_word": "2",
	"testament": "1",
	"tag": "Compassion",
	"timestamp": "2015-07-03 10:15:42",
	"description": "Verily I say unto you, Inasmuch as ye have done it unto one of the least of these my brethren, ye have done it unto me."
}, {
	"id": "119",
	"verses": "Put on the full armor of God, so that you will be able to stand firm against the schemes of the devil.",
	"book": "Ephesians",
	"chapter": "6",
	"verse_num": "11",
	"christ_word": "24",
	"testament": "1",
	"tag": "Protection",
	"timestamp": "2015-07-04 07:55:19",
	"description": "Put on the whole armour of God, that ye may be able to stand against the wiles of the devil."
}, {
	"id": "120",
	"verses": "The god of this age has blinded the minds of unbelievers, so that they cannot see the light of the gospel that displays the glory of Christ, who is the image of God.",
	"book": "2 Corinthians",
	"chapter": "4",
	"verse_num": "4",
	"christ_word": "22",
	"testament": "1",
	"tag": "Blindness",
	"timestamp": "2015-07-05 07:45:48",
	"description": "The god of this world hath blinded the minds of them which believe not, lest the light of the glorious gospel of Christ, who is the image of God, should shine unto them."
}, {
	"id": "121",
	"verses": "For the gate is narrow and the way is hard that leads to life, and those who find it are few.",
	"book": "Matthew",
	"chapter": "7",
	"verse_num": "14",
	"christ_word": "3",
	"testament": "1",
	"tag": "Life",
	"timestamp": "2015-07-06 06:57:15",
	"description": "Because strait is the gate, and narrow is the way, which leadeth unto life, and few there be that find it."
}, {
	"id": "122",
	"verses": "Watch and pray that you may not enter into temptation. The spirit indeed is willing, but the flesh is weak.",
	"book": "Mark",
	"chapter": "14",
	"verse_num": "38",
	"christ_word": "3",
	"testament": "1",
	"tag": "Prayer",
	"timestamp": "2015-07-07 09:41:50",
	"description": "Watch ye and pray, lest ye enter into temptation. The spirit truly is ready, but the flesh is weak."
}, {
	"id": "123",
	"verses": "Humble yourselves in the sight of the Lord, and he shall lift you up.",
	"book": "James",
	"chapter": "4",
	"verse_num": "10",
	"christ_word": "25",
	"testament": "1",
	"tag": "Humble",
	"timestamp": "2015-07-08 09:52:24",
	"description": "Humble yourselves in the sight of the Lord, and he shall lift you up."
}, {
	"id": "124",
	"verses": "Salvation is found in no one else, for there is no other name under heaven given to mankind by which we must be saved.",
	"book": "Acts",
	"chapter": "4",
	"verse_num": "12",
	"christ_word": "22",
	"testament": "1",
	"tag": "Salvation",
	"timestamp": "2015-07-09 10:45:44",
	"description": "Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved."
}, {
	"id": "125",
	"verses": "I will give you a new heart and put a new spirit in you; I will remove from you your heart of stone and give you a heart of flesh.",
	"book": "Ezekiel",
	"chapter": "36",
	"verse_num": "26",
	"christ_word": "22",
	"testament": "0",
	"tag": "Life",
	"timestamp": "2015-07-10 06:13:32",
	"description": "A new heart also will I give you, and a new spirit will I put within you: and I will take away the stony heart out of your flesh, and I will give you an heart of flesh."
}, {
	"id": "126",
	"verses": "I will make with them an everlasting covenant, that I will not turn away from doing good to them. And I will put the fear of me in their hearts, that they may not turn from me. I will rejoice in doing them good, and I will plant them in this land in faithfulness, with all my heart and all my soul.",
	"book": "Jeremiah",
	"chapter": "32",
	"verse_num": "40-41",
	"christ_word": "21",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-07-11 11:57:58",
	"description": "And I will make an everlasting covenant with them, that I will not turn away from them, to do them good; but I will put my fear in their hearts, that they shall not depart from me. Yea, I will rejoice over them to do them good, and I will plant them in this land assuredly with my whole heart and with my whole soul."
}, {
	"id": "127",
	"verses": "I have said these things to you, that in me you may have peace. In the world you will have tribulation. But take heart; I have overcome the world.",
	"book": "John",
	"chapter": "16",
	"verse_num": "33",
	"christ_word": "3",
	"testament": "1",
	"tag": "Peace",
	"timestamp": "2015-07-12 10:11:11",
	"description": "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world."
}, {
	"id": "128",
	"verses": "Whatever you do, do your work heartily, as for the Lord rather than for men.",
	"book": "Colossians",
	"chapter": "3",
	"verse_num": "23",
	"christ_word": "24",
	"testament": "1",
	"tag": "Effort",
	"timestamp": "2015-07-13 07:50:57",
	"description": "And whatsoever ye do, do it heartily, as to the Lord, and not unto men."
}, {
	"id": "129",
	"verses": "There is no fear in love, but perfect love casts out fear. For fear has to do with punishment, and whoever fears has not been perfected in love. We love because he first loved us.",
	"book": "1 John",
	"chapter": "4",
	"verse_num": "18-19",
	"christ_word": "21",
	"testament": "1",
	"tag": "Love",
	"timestamp": "2015-07-14 07:09:35",
	"description": "There is no fear in love; but perfect love casteth out fear: because fear hath torment. He that feareth is not made perfect in love. We love him, because he first loved us."
}, {
	"id": "130",
	"verses": "For the eyes of the LORD run to and fro throughout the whole earth, to show himself strong in the behalf of them whose heart is perfect toward him...",
	"book": "2 Chronicles",
	"chapter": "16",
	"verse_num": "9",
	"christ_word": "25",
	"testament": "0",
	"tag": "Perfection",
	"timestamp": "2015-07-15 04:42:28",
	"description": "For the eyes of the LORD run to and fro throughout the whole earth, to shew himself strong in the behalf of them whose heart is perfect toward him..."
}, {
	"id": "131",
	"verses": "Blessed rather are those who hear the word of God and obey it.",
	"book": "Luke",
	"chapter": "11",
	"verse_num": "28",
	"christ_word": "2",
	"testament": "1",
	"tag": "Blessing",
	"timestamp": "2015-07-16 05:22:43",
	"description": "Blessed are they that hear the word of God, and keep it."
}, {
	"id": "134",
	"verses": "Naked I came from my mother's womb, and naked I will depart. The LORD gave and the LORD has taken away; may the name of the LORD be praised.",
	"book": "Job",
	"chapter": "1",
	"verse_num": "21",
	"christ_word": "22",
	"testament": "0",
	"tag": "Faith",
	"timestamp": "2015-07-17 09:36:34",
	"description": "Naked came I out of my mother's womb, and naked shall I return thither: the LORD gave, and the LORD hath taken away; blessed be the name of the LORD."
}, {
	"id": "135",
	"verses": "Immediately the father of the child cried out, and said with tears, Lord, I believe; help my unbelief.",
	"book": "Mark",
	"chapter": "9",
	"verse_num": "24",
	"christ_word": "26",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-07-18 09:18:27",
	"description": "And straightway the father of the child cried out, and said with tears, Lord, I believe; help thou mine unbelief."
}, {
	"id": "136",
	"verses": "I praise you, Father, Lord of heaven and earth, because you have hidden these things from the wise and learned, and revealed them to little children.",
	"book": "Matthew",
	"chapter": "11",
	"verse_num": "25",
	"christ_word": "2",
	"testament": "1",
	"tag": "Wisdom",
	"timestamp": "2015-07-19 08:10:49",
	"description": "I thank thee, O Father, Lord of heaven and earth, because thou hast hid these things from the wise and prudent, and hast revealed them unto babes."
}, {
	"id": "137",
	"verses": "But sanctify the Lord God in your hearts: and be ready always to give an answer to every man that asks you a reason of the hope that is in you with meekness and fear.",
	"book": "1 Peter",
	"chapter": "3",
	"verse_num": "15",
	"christ_word": "25",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-07-20 09:23:28",
	"description": "But sanctify the Lord God in your hearts: and be ready always to give an answer to every man that asketh you a reason of the hope that is in you with meekness and fear."
}, {
	"id": "138",
	"verses": "Better is the end of a thing than its beginning, and the patient in spirit is better than the proud in spirit.",
	"book": "Ecclesiastes",
	"chapter": "7",
	"verse_num": "8",
	"christ_word": "21",
	"testament": "0",
	"tag": "Patience",
	"timestamp": "2015-07-21 07:16:41",
	"description": "Better is the end of a thing than the beginning thereof: and the patient in spirit is better than the proud in spirit."
}, {
	"id": "139",
	"verses": "So we do not lose heart. Though our outer self is wasting away, our inner self is being renewed day by day. For this light momentary affliction is preparing for us an eternal weight of glory beyond all comparison.",
	"book": "2 Corinthians",
	"chapter": "4",
	"verse_num": "16-17",
	"christ_word": "21",
	"testament": "1",
	"tag": "Suffering",
	"timestamp": "2015-07-22 09:48:51",
	"description": "For which cause we faint not; but though our outward man perish, yet the inward man is renewed day by day. For our light affliction, which is but for a moment, worketh for us a far more exceeding and eternal weight of glory."
}, {
	"id": "140",
	"verses": "And this is the condemnation, that light is come into the world, and men loved darkness rather than light, because their deeds were evil. For every one that does evil hates the light, neither comes to the light, lest his deeds should be reproved.",
	"book": "John",
	"chapter": "3",
	"verse_num": "19-20",
	"christ_word": "5",
	"testament": "1",
	"tag": "Evil",
	"timestamp": "2015-07-23 05:56:43",
	"description": "And this is the condemnation, that light is come into the world, and men loved darkness rather than light, because their deeds were evil. For every one that doeth evil hateth the light, neither cometh to the light, lest his deeds should be reproved."
}, {
	"id": "141",
	"verses": "You will seek me and find me, when you seek me with all your heart.",
	"book": "Jeremiah",
	"chapter": "29",
	"verse_num": "13",
	"christ_word": "21",
	"testament": "0",
	"tag": "Heart",
	"timestamp": "2015-07-24 09:36:26",
	"description": "And ye shall seek me, and find me, when ye shall search for me with all your heart."
}, {
	"id": "142",
	"verses": "This is the day that the LORD has made; let us rejoice and be glad in it.",
	"book": "Psalms",
	"chapter": "118",
	"verse_num": "24",
	"christ_word": "21",
	"testament": "0",
	"tag": "Happiness",
	"timestamp": "2015-07-25 09:31:37",
	"description": "This is the day which the LORD hath made; we will rejoice and be glad in it."
}, {
	"id": "143",
	"verses": "I am the resurrection and the life. Whoever believes in me, though he die, yet shall he live, and everyone who lives and believes in me shall never die. Do you believe this?",
	"book": "John",
	"chapter": "11",
	"verse_num": "25-26",
	"christ_word": "3",
	"testament": "1",
	"tag": "Life",
	"timestamp": "2015-07-26 10:00:28",
	"description": "I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live: And whosoever liveth and believeth in me shall never die. Believest thou this?"
}, {
	"id": "144",
	"verses": "For the one who sows to his own flesh will from the flesh reap corruption, but the one who sows to the Spirit will from the Spirit reap eternal life.",
	"book": "Galatians",
	"chapter": "6",
	"verse_num": "8",
	"christ_word": "24",
	"testament": "1",
	"tag": "Life",
	"timestamp": "2015-07-27 06:29:14",
	"description": "For he that soweth to his flesh shall of the flesh reap corruption; but he that soweth to the Spirit shall of the Spirit reap life everlasting."
}, {
	"id": "145",
	"verses": "I can do all things through Christ who strengthens me.",
	"book": "Philippians",
	"chapter": "4",
	"verse_num": "13",
	"christ_word": "26",
	"testament": "1",
	"tag": "Strength",
	"timestamp": "2015-07-28 09:28:00",
	"description": "I can do all things through Christ which strengtheneth me."
}, {
	"id": "146",
	"verses": "Therefore the LORD longs to be gracious to you, And therefore He waits on high to have compassion on you. For the LORD is a God of justice; How blessed are all those who long for Him.",
	"book": "Isaiah",
	"chapter": "30",
	"verse_num": "18",
	"christ_word": "24",
	"testament": "0",
	"tag": "Compassion",
	"timestamp": "2015-07-29 09:34:54",
	"description": "Therefore will the LORD wait, that he may be gracious unto you, and therefore will he be exalted, that he may have mercy upon you: for the LORD is a God of judgment: blessed are all they that wait for him."
}, {
	"id": "147",
	"verses": "And we know that for those who love God all things work together for good, for those who are called according to his purpose.",
	"book": "Romans",
	"chapter": "8",
	"verse_num": "28",
	"christ_word": "21",
	"testament": "1",
	"tag": "Love",
	"timestamp": "2015-07-30 10:07:04",
	"description": "And we know that all things work together for good to them that love God, to them who are the called according to his purpose."
}, {
	"id": "148",
	"verses": "Cast all your anxiety on him because he cares for you.",
	"book": "1 Peter",
	"chapter": "5",
	"verse_num": "7",
	"christ_word": "22",
	"testament": "1",
	"tag": "Anxious",
	"timestamp": "2015-08-01 11:59:49",
	"description": "Casting all your care upon him; for he careth for you."
}, {
	"id": "149",
	"verses": "Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.",
	"book": "2 Corinthians",
	"chapter": "5",
	"verse_num": "17",
	"christ_word": "21",
	"testament": "1",
	"tag": "Life",
	"timestamp": "2015-08-02 11:34:04",
	"description": "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new."
}, {
	"id": "150",
	"verses": "I am the LORD; I have called you in righteousness; I will take you by the hand and keep you; I will give you as a covenant for the people, a light for the nations, to open the eyes that are blind, to bring out the prisoners from the dungeon, from the prison those who sit in darkness.",
	"book": "Isaiah",
	"chapter": "42",
	"verse_num": "6-7",
	"christ_word": "21",
	"testament": "0",
	"tag": "Encouragement",
	"timestamp": "2015-08-03 06:07:47",
	"description": "I the LORD have called thee in righteousness, and will hold thine hand, and will keep thee, and give thee for a covenant of the people, for a light of the Gentiles; To open the blind eyes, to bring out the prisoners from the prison, and them that sit in darkness out of the prison house."
}, {
	"id": "151",
	"verses": "Beloved, let us love one another, for love is from God, and whoever loves has been born of God and knows God.",
	"book": "1 John",
	"chapter": "4",
	"verse_num": "7",
	"christ_word": "21",
	"testament": "1",
	"tag": "Love",
	"timestamp": "2015-08-04 10:09:39",
	"description": "Beloved, let us love one another: for love is of God; and every one that loveth is born of God, and knoweth God."
}, {
	"id": "152",
	"verses": "But let justice roll down like waters, and righteousness like an ever-flowing stream.",
	"book": "Amos",
	"chapter": "5",
	"verse_num": "24",
	"christ_word": "21",
	"testament": "0",
	"tag": "Justice",
	"timestamp": "2015-08-05 11:10:31",
	"description": "But let judgment run down as waters, and righteousness as a mighty stream."
}, {
	"id": "153",
	"verses": "For God so loved the world, that He gave His only begotten Son, that whoever believes in Him shall not perish, but have eternal life.",
	"book": "John",
	"chapter": "3",
	"verse_num": "16",
	"christ_word": "4",
	"testament": "1",
	"tag": "Love",
	"timestamp": "2015-08-06 10:16:52",
	"description": "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life."
}, {
	"id": "154",
	"verses": "And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.",
	"book": "Philippians",
	"chapter": "4",
	"verse_num": "7",
	"christ_word": "22",
	"testament": "1",
	"tag": "Peace",
	"timestamp": "2015-08-07 10:26:51",
	"description": "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus."
}, {
	"id": "155",
	"verses": "It is not what goes into the mouth that defiles a person, but what comes out of the mouth; this defiles a person.",
	"book": "Matthew",
	"chapter": "15",
	"verse_num": "11",
	"christ_word": "3",
	"testament": "1",
	"tag": "Integrity",
	"timestamp": "2015-08-08 08:58:36",
	"description": "Not that which goeth into the mouth defileth a man; but that which cometh out of the mouth, this defileth a man."
}, {
	"id": "156",
	"verses": "But I say to you, Love your enemies and pray for those who persecute you, so that you may be sons of your Father who is in heaven. For he makes his sun rise on the evil and on the good, and sends rain on the just and on the unjust.",
	"book": "Matthew",
	"chapter": "5",
	"verse_num": "44-45",
	"christ_word": "3",
	"testament": "1",
	"tag": "Love",
	"timestamp": "2015-08-09 10:23:51",
	"description": "But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you; That ye may be the children of your Father which is in heaven: for he maketh his sun to rise on the evil and on the good, and sendeth rain on the just and on the unjust."
}, {
	"id": "157",
	"verses": "May the LORD watch between you and me when we are absent one from the other.",
	"book": "Genesis",
	"chapter": "31",
	"verse_num": "49",
	"christ_word": "24",
	"testament": "0",
	"tag": "Relationship",
	"timestamp": "2015-08-10 09:25:09",
	"description": "The LORD watch between me and thee, when we are absent one from another."
}, {
	"id": "158",
	"verses": "From the ends of the earth I call to you, I call as my heart grows faint; lead me to the rock that is higher than I.",
	"book": "Psalm",
	"chapter": "61",
	"verse_num": "2",
	"christ_word": "22",
	"testament": "0",
	"tag": "Hardship",
	"timestamp": "2015-08-11 10:34:42",
	"description": "From the end of the earth will I cry unto thee, when my heart is overwhelmed: lead me to the rock that is higher than I."
}, {
	"id": "159",
	"verses": "For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.",
	"book": "Romans",
	"chapter": "8",
	"verse_num": "38-39",
	"christ_word": "22",
	"testament": "1",
	"tag": "Love",
	"timestamp": "2015-08-12 08:17:02",
	"description": "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come, Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord."
}, {
	"id": "160",
	"verses": "I run in the path of your commandments, for you have set my heart free.",
	"book": "Psalm",
	"chapter": "119",
	"verse_num": "32",
	"christ_word": "28",
	"testament": "0",
	"tag": "Freedom",
	"timestamp": "2015-08-13 05:58:19",
	"description": "I will run the way of thy commandments, when thou shalt enlarge my heart."
}, {
	"id": "161",
	"verses": "He has shown you, O mortal, what is good. And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God.",
	"book": "Micah",
	"chapter": "6",
	"verse_num": "8",
	"christ_word": "22",
	"testament": "0",
	"tag": "Virtue",
	"timestamp": "2015-08-14 05:54:24",
	"description": "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?"
}, {
	"id": "162",
	"verses": "No weapon that is formed against you shall prosper; and every tongue that shall rise against you in judgment you shall condemn. This is the heritage of the servants of the LORD, and their righteousness is of me, said the LORD.",
	"book": "Isaiah",
	"chapter": "54",
	"verse_num": "17",
	"christ_word": "25",
	"testament": "0",
	"tag": "Adversary",
	"timestamp": "2015-08-15 09:15:43",
	"description": "No weapon that is formed against thee shall prosper; and every tongue that shall rise against thee in judgment thou shalt condemn. This is the heritage of the servants of the LORD, and their righteousness is of me, saith the LORD."
}, {
	"id": "163",
	"verses": "Those who are well have no need of a physician, but those who are sick. I have not come to call the righteous but sinners to repentance.",
	"book": "Luke",
	"chapter": "5",
	"verse_num": "31-32",
	"christ_word": "3",
	"testament": "1",
	"tag": "Healing",
	"timestamp": "2015-08-16 07:40:39",
	"description": "They that are whole need not a physician; but they that are sick. I came not to call the righteous, but sinners to repentance."
}, {
	"id": "164",
	"verses": "He must increase, but I must decrease.",
	"book": "John",
	"chapter": "3",
	"verse_num": "30",
	"christ_word": "21",
	"testament": "1",
	"tag": "Humble",
	"timestamp": "2015-08-17 10:35:47",
	"description": "He must increase, but I must decrease."
}, {
	"id": "165",
	"verses": "And many of those who sleep in the dust of the earth shall awake, some to everlasting life, and some to shame and everlasting contempt. And those who are wise shall shine like the brightness of the sky above; and those who turn many to righteousness, like the stars forever and ever.",
	"book": "Daniel",
	"chapter": "12",
	"verse_num": "2-3",
	"christ_word": "21",
	"testament": "0",
	"tag": "Resurrection",
	"timestamp": "2015-08-18 08:24:38",
	"description": "And many of them that sleep in the dust of the earth shall awake, some to everlasting life, and some to shame and everlasting contempt. And they that be wise shall shine as the brightness of the firmament; and they that turn many to righteousness as the stars for ever and ever."
}, {
	"id": "166",
	"verses": "Rejoice always, pray without ceasing, give thanks in all circumstances; for this is the will of God in Christ Jesus for you.",
	"book": "1 Thessalonians",
	"chapter": "5",
	"verse_num": "16-18",
	"christ_word": "21",
	"testament": "1",
	"tag": "Happiness",
	"timestamp": "2015-08-19 09:53:25",
	"description": "Rejoice evermore. Pray without ceasing. In every thing give thanks: for this is the will of God in Christ Jesus concerning you."
}, {
	"id": "167",
	"verses": "For God did not send his Son into the world to condemn the world, but in order that the world might be saved through him.",
	"book": "John",
	"chapter": "3",
	"verse_num": "17",
	"christ_word": "3",
	"testament": "1",
	"tag": "Mercy",
	"timestamp": "2015-08-20 11:12:16",
	"description": "For God sent not his Son into the world to condemn the world; but that the world through him might be saved."
}, {
	"id": "168",
	"verses": "Trust in the LORD with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths.",
	"book": "Proverbs",
	"chapter": "3",
	"verse_num": "5-6",
	"christ_word": "21",
	"testament": "0",
	"tag": "Knowledge",
	"timestamp": "2015-08-21 07:41:25",
	"description": "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths."
}, {
	"id": "169",
	"verses": "Do not conform to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God's will is--his good, pleasing and perfect will.",
	"book": "Romans",
	"chapter": "12",
	"verse_num": "2",
	"christ_word": "22",
	"testament": "1",
	"tag": "Knowledge",
	"timestamp": "2015-08-22 10:25:18",
	"description": "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God."
}, {
	"id": "170",
	"verses": "But now we are released from the law, having died to that which held us captive, so that we serve in the new way of the Spirit and not in the old way of the written code.",
	"book": "Romans",
	"chapter": "7",
	"verse_num": "6",
	"christ_word": "21",
	"testament": "1",
	"tag": "Freedom",
	"timestamp": "2015-08-23 11:56:35",
	"description": "But now we are delivered from the law, that being dead wherein we were held; that we should serve in newness of spirit, and not in the oldness of the letter."
}, {
	"id": "171",
	"verses": "For consider your calling, brothers: not many of you were wise according to worldly standards, not many were powerful, not many were of noble birth. But God chose what is foolish in the world to shame the wise; God chose what is weak in the world to shame the strong.",
	"book": "1 Corinthians",
	"chapter": "1",
	"verse_num": "26-27",
	"christ_word": "21",
	"testament": "1",
	"tag": "Grace",
	"timestamp": "2015-08-24 09:35:38",
	"description": "For ye see your calling, brethren, how that not many wise men after the flesh, not many mighty, not many noble, are called: But God hath chosen the foolish things of the world to confound the wise; and God hath chosen the weak things of the world to confound the things which are mighty."
}, {
	"id": "172",
	"verses": "A new commandment I give to you, that you love one another: just as I have loved you, you also are to love one another. By this all people will know that you are my disciples, if you have love for one another.",
	"book": "John",
	"chapter": "13",
	"verse_num": "34-35",
	"christ_word": "3",
	"testament": "1",
	"tag": "Love",
	"timestamp": "2015-08-25 08:52:44",
	"description": "A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another. By this shall all men know that ye are my disciples, if ye have love one to another."
}, {
	"id": "173",
	"verses": "For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, plans to give you hope and a future.",
	"book": "Jeremiah",
	"chapter": "29",
	"verse_num": "11",
	"christ_word": "22",
	"testament": "0",
	"tag": "Hope",
	"timestamp": "2015-08-26 03:59:01",
	"description": "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end."
}, {
	"id": "174",
	"verses": "But they who wait for the LORD shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint.",
	"book": "Isaiah",
	"chapter": "40",
	"verse_num": "31",
	"christ_word": "21",
	"testament": "0",
	"tag": "Strength",
	"timestamp": "2015-08-27 06:58:38",
	"description": "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint."
}, {
	"id": "175",
	"verses": "I know that my redeemer lives, and that in the end he will stand on the earth.",
	"book": "Job",
	"chapter": "19",
	"verse_num": "25",
	"christ_word": "22",
	"testament": "0",
	"tag": "Prophesy",
	"timestamp": "2015-08-28 08:09:19",
	"description": "For I know that my redeemer liveth, and that he shall stand at the latter day upon the earth."
}, {
	"id": "176",
	"verses": "My grace is sufficient for you, for my power is made perfect in weakness.",
	"book": "2 Corinthians",
	"chapter": "12",
	"verse_num": "9",
	"christ_word": "2",
	"testament": "1",
	"tag": "Strength",
	"timestamp": "2015-08-30 04:16:56",
	"description": "My grace is sufficient for thee: for my strength is made perfect in weakness."
}, {
	"id": "177",
	"verses": "And the prayer of faith will save the one who is sick, and the Lord will raise him up. And if he has committed sins, he will be forgiven.",
	"book": "James",
	"chapter": "5",
	"verse_num": "15",
	"christ_word": "21",
	"testament": "1",
	"tag": "Prayer",
	"timestamp": "2015-09-01 08:00:57",
	"description": "And the prayer of faith shall save the sick, and the Lord shall raise him up; and if he have committed sins, they shall be forgiven him."
}, {
	"id": "179",
	"verses": "It is a trustworthy statement, deserving full acceptance, that Christ Jesus came into the world to save sinners, among whom I am foremost of all.",
	"book": "1 Timothy",
	"chapter": "1",
	"verse_num": "15",
	"christ_word": "24",
	"testament": "1",
	"tag": "Salvation",
	"timestamp": "2015-09-02 09:12:57",
	"description": "This is a faithful saying, and worthy of all acceptation, that Christ Jesus came into the world to save sinners; of whom I am chief."
}, {
	"id": "180",
	"verses": "Do not be overcome by evil, but overcome evil with good.",
	"book": "Romans",
	"chapter": "12",
	"verse_num": "21",
	"christ_word": "22",
	"testament": "1",
	"tag": "Goodness",
	"timestamp": "2015-09-03 07:18:22",
	"description": "Be not overcome of evil, but overcome evil with good."
}, {
	"id": "181",
	"verses": "Truly I tell you, if you have faith as small as a mustard seed, you can say to this mountain, 'Move from here to there,' and it will move. Nothing will be impossible for you.",
	"book": "Matthew",
	"chapter": "17",
	"verse_num": "20",
	"christ_word": "2",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-09-04 05:23:33",
	"description": "For verily I say unto you, If ye have faith as a grain of mustard seed, ye shall say unto this mountain, Remove hence to yonder place; and it shall remove; and nothing shall be impossible unto you."
}, {
	"id": "182",
	"verses": "You search the Scriptures because you think that in them you have eternal life; and it is they that bear witness about me, yet you refuse to come to me that you may have life.",
	"book": "John",
	"chapter": "5",
	"verse_num": "39-40",
	"christ_word": "3",
	"testament": "1",
	"tag": "Life",
	"timestamp": "2015-09-05 06:15:44",
	"description": "Search the scriptures; for in them ye think ye have eternal life: and they are they which testify of me. And ye will not come to me, that ye might have life."
}, {
	"id": "183",
	"verses": "For to me, to live is Christ and to die is gain.",
	"book": "Philippians",
	"chapter": "1",
	"verse_num": "21",
	"christ_word": "22",
	"testament": "1",
	"tag": "Life",
	"timestamp": "2015-09-06 10:12:49",
	"description": "For to me to live is Christ, and to die is gain."
}, {
	"id": "184",
	"verses": "For by grace you have been saved through faith; and that not of yourselves, it is the gift of God.",
	"book": "Ephesians",
	"chapter": "2",
	"verse_num": "8",
	"christ_word": "24",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-09-07 08:21:20",
	"description": "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God."
}, {
	"id": "185",
	"verses": "Treat others the same way you want them to treat you.",
	"book": "Luke",
	"chapter": "6",
	"verse_num": "31",
	"christ_word": "4",
	"testament": "1",
	"tag": "Wisdom",
	"timestamp": "2015-09-08 08:49:23",
	"description": "And as ye would that men should do to you, do ye also to them likewise."
}, {
	"id": "186",
	"verses": "Rejoice not over me, O my enemy; when I fall, I shall rise; when I sit in darkness, the LORD will be a light to me.",
	"book": "Micah",
	"chapter": "7",
	"verse_num": "8",
	"christ_word": "21",
	"testament": "0",
	"tag": "Adversary",
	"timestamp": "2015-09-09 06:20:38",
	"description": "Rejoice not against me, O mine enemy: when I fall, I shall arise; when I sit in darkness, the LORD shall be a light unto me."
}, {
	"id": "187",
	"verses": "But if any of you lacks wisdom, let him ask of God, who gives to all generously and without reproach, and it will be given to him.",
	"book": "James",
	"chapter": "1",
	"verse_num": "5",
	"christ_word": "24",
	"testament": "1",
	"tag": "Wisdom",
	"timestamp": "2015-09-10 06:23:37",
	"description": "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him."
}, {
	"id": "188",
	"verses": "There is no longer Jew or Gentile, slave or free, male and female. For you are all one in Christ Jesus.",
	"book": "Galatians",
	"chapter": "3",
	"verse_num": "28",
	"christ_word": "27",
	"testament": "1",
	"tag": "Grace",
	"timestamp": "2015-09-11 05:50:56",
	"description": "There is neither Jew nor Greek, there is neither bond nor free, there is neither male nor female: for ye are all one in Christ Jesus."
}, {
	"id": "189",
	"verses": "Though you have not seen him, you love him; and even though you do not see him now, you believe in him and are filled with an inexpressible and glorious joy, for you are receiving the end result of your faith, the salvation of your souls.",
	"book": "1 Peter",
	"chapter": "1",
	"verse_num": "8-9",
	"christ_word": "22",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-09-12 06:30:03",
	"description": "Whom having not seen, ye love; in whom, though now ye see him not, yet believing, ye rejoice with joy unspeakable and full of glory: Receiving the end of your faith, even the salvation of your souls."
}, {
	"id": "190",
	"verses": "Behold, I stand at the door and knock; if anyone hears My voice and opens the door, I will come in to him and will dine with him, and he with Me.",
	"book": "Revelation",
	"chapter": "3",
	"verse_num": "20",
	"christ_word": "4",
	"testament": "1",
	"tag": "Salvation",
	"timestamp": "2015-09-14 05:58:51",
	"description": "Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him, and will sup with him, and he with me."
}, {
	"id": "191",
	"verses": "For all have sinned and fall short of the glory of God.",
	"book": "Romans",
	"chapter": "3",
	"verse_num": "23",
	"christ_word": "21",
	"testament": "1",
	"tag": "Sin",
	"timestamp": "2015-09-15 09:00:08",
	"description": "For all have sinned, and come short of the glory of God."
}, {
	"id": "192",
	"verses": "In peace I will lie down and sleep, for you alone, LORD, make me dwell in safety.",
	"book": "Psalm",
	"chapter": "4",
	"verse_num": "8",
	"christ_word": "22",
	"testament": "0",
	"tag": "Stress",
	"timestamp": "2015-09-17 06:29:58",
	"description": "I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety."
}, {
	"id": "193",
	"verses": "Do not merely listen to the word, and so deceive yourselves. Do what it says.",
	"book": "James",
	"chapter": "1",
	"verse_num": "22",
	"christ_word": "22",
	"testament": "1",
	"tag": "Effort",
	"timestamp": "2015-09-19 06:26:48",
	"description": "But be ye doers of the word, and not hearers only, deceiving your own selves."
}, {
	"id": "194",
	"verses": "There is a way that seems right to a man, but its end is the way to death.",
	"book": "Proverbs",
	"chapter": "14",
	"verse_num": "12",
	"christ_word": "21",
	"testament": "0",
	"tag": "Wisdom",
	"timestamp": "2015-09-21 06:24:08",
	"description": "There is a way which seemeth right unto a man, but the end thereof are the ways of death."
}, {
	"id": "195",
	"verses": "Your word I have treasured in my heart, that I may not sin against You.",
	"book": "Psalm",
	"chapter": "119",
	"verse_num": "11",
	"christ_word": "24",
	"testament": "0",
	"tag": "Sin",
	"timestamp": "2015-09-23 09:35:17",
	"description": "Thy word have I hid in mine heart, that I might not sin against thee."
}, {
	"id": "196",
	"verses": "Do not neglect to show hospitality to strangers, for by this some have entertained angels without knowing it.",
	"book": "Hebrews",
	"chapter": "13",
	"verse_num": "2",
	"christ_word": "24",
	"testament": "1",
	"tag": "Hospitality",
	"timestamp": "2015-09-25 10:12:07",
	"description": "Be not forgetful to entertain strangers: for thereby some have entertained angels unawares."
}, {
	"id": "197",
	"verses": "Blessed are you when others revile you and persecute you and utter all kinds of evil against you falsely on my account. Rejoice and be glad, for your reward is great in heaven, for so they persecuted the prophets who were before you.",
	"book": "Matthew",
	"chapter": "5",
	"verse_num": "11-12",
	"christ_word": "3",
	"testament": "1",
	"tag": "Persecution",
	"timestamp": "2015-09-28 06:50:19",
	"description": "Blessed are ye, when men shall revile you, and persecute you, and shall say all manner of evil against you falsely, for my sake. Rejoice, and be exceeding glad: for great is your reward in heaven: for so persecuted they the prophets which were before you."
}, {
	"id": "198",
	"verses": "The LORD opens the eyes of the blind. The LORD lifts up those who are bowed down; the LORD loves the righteous.",
	"book": "Psalm",
	"chapter": "146",
	"verse_num": "8",
	"christ_word": "21",
	"testament": "0",
	"tag": "Hope",
	"timestamp": "2015-10-01 07:33:34",
	"description": "The LORD openeth the eyes of the blind: the LORD raiseth them that are bowed down: the LORD loveth the righteous:"
}, {
	"id": "199",
	"verses": "Shout joyfully to the LORD, all the earth; break forth and sing for joy and sing praises.",
	"book": "Psalm",
	"chapter": "98",
	"verse_num": "4",
	"christ_word": "24",
	"testament": "0",
	"tag": "Happiness",
	"timestamp": "2015-10-04 10:01:59",
	"description": "Make a joyful noise unto the LORD, all the earth: make a loud noise, and rejoice, and sing praise."
}, {
	"id": "200",
	"verses": "For the message of the cross is foolishness to those who are perishing, but to us who are being saved it is the power of God.",
	"book": "1 Corinthians",
	"chapter": "1",
	"verse_num": "18",
	"christ_word": "22",
	"testament": "1",
	"tag": "Truth",
	"timestamp": "2015-10-09 10:27:34",
	"description": "For the preaching of the cross is to them that perish foolishness; but unto us which are saved it is the power of God."
}, {
	"id": "201",
	"verses": "You are the salt of the earth... You are the light of the world.",
	"book": "Matthew",
	"chapter": "5",
	"verse_num": "13-14",
	"christ_word": "3",
	"testament": "1",
	"tag": "Encouragement",
	"timestamp": "2015-10-11 10:09:20",
	"description": "Ye are the salt of the earth... Ye are the light of the world."
}, {
	"id": "202",
	"verses": "No one can serve two masters. Either you will hate the one and love the other, or you will be devoted to the one and despise the other. You cannot serve both God and money.",
	"book": "Matthew",
	"chapter": "6",
	"verse_num": "24",
	"christ_word": "2",
	"testament": "1",
	"tag": "Money",
	"timestamp": "2015-10-15 23:10:41",
	"description": "No man can serve two masters: for either he will hate the one, and love the other; or else he will hold to the one, and despise the other. Ye cannot serve God and mammon."
}, {
	"id": "203",
	"verses": "Seek the LORD while he may be found; call upon him while he is near.",
	"book": "Isaiah",
	"chapter": "55",
	"verse_num": "6",
	"christ_word": "21",
	"testament": "0",
	"tag": "Faith",
	"timestamp": "2015-10-18 08:29:02",
	"description": "Seek ye the LORD while he may be found, call ye upon him while he is near."
}, {
	"id": "204",
	"verses": "For this is a gracious thing, when, mindful of God, one endures sorrows while suffering unjustly.",
	"book": "1 Peter",
	"chapter": "2",
	"verse_num": "19",
	"christ_word": "21",
	"testament": "1",
	"tag": "Persecution",
	"timestamp": "2015-10-21 09:53:51",
	"description": "For this is thankworthy, if a man for conscience toward God endure grief, suffering wrongfully."
}, {
	"id": "205",
	"verses": "Now faith is the assurance of things hoped for, the conviction of things not seen.",
	"book": "Hebrews",
	"chapter": "11",
	"verse_num": "1",
	"christ_word": "21",
	"testament": "1",
	"tag": "Faith",
	"timestamp": "2015-10-24 10:53:51",
	"description": "Now faith is the substance of things hoped for, the evidence of things not seen."
}, {
	"id": "206",
	"verses": "I will turn their mourning into gladness; I will give them comfort and joy instead of sorrow.",
	"book": "Jeremiah",
	"chapter": "31",
	"verse_num": "13",
	"christ_word": "22",
	"testament": "0",
	"tag": "Hope",
	"timestamp": "2015-11-01 09:52:03",
	"description": "I will turn their mourning into joy, and will comfort them, and make them rejoice from their sorrow."
}, {
	"id": "207",
	"verses": "How sweet are your words to my taste, sweeter than honey to my mouth!",
	"book": "Psalm",
	"chapter": "119",
	"verse_num": "103",
	"christ_word": "21",
	"testament": "0",
	"tag": "Worship",
	"timestamp": "2015-11-09 23:43:29",
	"description": "How sweet are thy words unto my taste! yea, sweeter than honey to my mouth!"
}, {
	"id": "208",
	"verses": "For in him we live and move and have our being. As some of your own poets have said, 'We are his offspring.'",
	"book": "Acts",
	"chapter": "17",
	"verse_num": "28",
	"christ_word": "22",
	"testament": "1",
	"tag": "Life",
	"timestamp": "2015-11-10 22:32:44",
	"description": "For in him we live, and move, and have our being; as certain also of your own poets have said, For we are also his offspring."
}, {
	"id": "209",
	"verses": "My flesh and my heart may fail, but God is the strength of my heart and my portion forever.",
	"book": "Psalm",
	"chapter": "73",
	"verse_num": "26",
	"christ_word": "21",
	"testament": "0",
	"tag": "Strength",
	"timestamp": "2015-11-29 09:42:31",
	"description": "My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever."
}]